import type { CriterionContent, CriterionStatus, ScenarioContent, ScenarioContentMap } from "./content-types";

/**
 * Demo calls 16 to 32 (SPECS positions): two Green without a booking, eight Amber, seven Red. Everything here is
 * invented. No figure of any kind appears: callers never volunteer a budget, and a cost question gets only the
 * approved line. Timestamps are generated from the length of each turn and always end inside the call's minutes.
 */

const OPEN =
  "Hello, thank you for calling Aangan Studio. I'm the studio's AI assistant, and this call is recorded so our designers have your details. How can I help you today?";
const PRICE_LINE =
  "Pricing depends on the site, the materials you choose, and the scope — your designer will walk you through it in detail at the consultation.";
const BOOK_INTRO =
  "Based on what you've told me, I'd like to set up a design call with one of our designers. It's a short video or phone call of about twenty minutes. Which day would suit you?";
const FIT_PHRASE = "This sounds like it may not be the right fit for us right now, but please do reach out if your plans change.";

const WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"];
const digits = (s: string) => s.split("").map((d) => WORDS[Number(d)]).join(" ");
const spell = (s: string) => s.split("").map((c) => (c === "." ? "dot" : c === "@" ? "at" : c === "_" ? "underscore" : c)).join(", ");
const phone = (n: number) => digits(`99999${String(n).padStart(5, "0")}`);

const hms = (t: number) => {
  const s = Math.floor(t);
  return `[${String(Math.floor(s / 3600)).padStart(2, "0")}:${String(Math.floor((s % 3600) / 60)).padStart(2, "0")}:${String(s % 60).padStart(2, "0")}]`;
};

/** Lines start with "A: " (agent) or "U: " (caller). Timestamps follow turn length and finish inside `seconds`. */
function tx(seconds: number, lines: string[]): string {
  const weight = lines.map((l) => 2.5 + l.split(/\s+/).length * 0.45);
  const total = weight.reduce((a, b) => a + b, 0);
  const scale = (seconds - 10) / total;
  let acc = 0;
  let prev = 0;
  return lines
    .map((l, i) => {
      const at = Math.max(prev + 1, 2 + acc * scale);
      prev = at;
      acc += weight[i];
      return `${hms(at)} ${l.startsWith("A:") ? "AGENT" : "USER"}: ${l.slice(3)}`;
    })
    .join("\n\n");
}

/** Booking flow shared by Green and Amber. */
function book(o: { dayReply: string; slots: string; pick: string; emailLocal: string; emailDomain: string; confirm: string }): string[] {
  const email = `${o.emailLocal}@${o.emailDomain}`;
  return [
    `A: ${BOOK_INTRO}`,
    `U: ${o.dayReply}`,
    `A: Let me check that for you. ${o.slots}`,
    `U: ${o.pick}`,
    "A: Could I have your email address so the joining details reach you?",
    `U: ${o.emailLocal} at ${o.emailDomain.replace(".", " dot ")}.`,
    `A: Let me read that back. ${spell(email)}. Is that right?`,
    "U: Yes, that's right.",
    `A: Thank you. ${o.confirm}`,
  ];
}

function close(n: number, recap: string): string[] {
  return [
    `A: Before we finish, is the best number to reach you ${phone(n)}?`,
    "U: Yes, that's right.",
    `A: Thank you. ${recap} Thank you for calling Aangan Studio, and have a good day.`,
    "U: Thank you, bye.",
  ];
}

type C = [CriterionStatus, string | null];
const crit = (real: C, area: C, time: C, decider: C): ScenarioContent["criteria"] => {
  const mk = ([status, evidence]: C): CriterionContent => ({ status, evidence });
  return { real_project: mk(real), service_area: mk(area), timeline: mk(time), budget: { status: "pass", evidence: null }, decision_maker: mk(decider) };
};

export const contentB: ScenarioContentMap = {
  // 16 Gauri Oak: Green, no free slot, designer to call
  16: {
    transcript: tx(378, [
      `A: ${OPEN}`,
      "U: Hi, I'm looking for an interior designer for my flat in Baner.",
      "A: Happy to help. May I have your name, please?",
      "U: Gauri Oak.",
      "A: Thank you, Gauri. Is this a home or an office?",
      "U: It's our home. A 3BHK apartment.",
      "A: Lovely. Roughly how big is it, in square feet?",
      "U: About fourteen hundred square feet.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, design and the full work. We don't want to run around managing contractors.",
      "A: That's clear. Is the site in Baner itself?",
      "U: Yes, in Baner, Pune.",
      "A: Good. When would you need the project complete?",
      "U: There's no hard date. We get possession in about a month, and we'd like to settle in three or four months after that.",
      "A: Thank you. I've noted that. How did you hear about the studio?",
      "U: Through your Instagram page. I loved the kitchen photos.",
      "A: That's lovely to hear. Is there anything you'd like to ask me before we look at a time?",
      "U: Yes, roughly what would a flat like mine come to?",
      `A: ${PRICE_LINE} I can book that for you right now if you'd like.`,
      "U: Okay, yes, let's do that.",
      `A: ${BOOK_INTRO}`,
      "U: Tomorrow afternoon, if possible.",
      "A: Let me check that for you. I'm sorry, there's no free slot tomorrow afternoon. Would another day work?",
      "U: Hmm. I'm travelling for work for the next few days. I can't say which day I'll be free.",
      "A: That's fine. We can do it the other way round. A designer will call you to fix a time that suits you.",
      "U: That works, thank you.",
      ...close(16, "I've noted a 3BHK home in Baner, design and execution, possession in about a month, and that a designer will call you to fix the design call."),
    ]),
    summary: "Gauri Oak, 3BHK in Baner (about 1,400 sq ft), wants full design and execution. No slot was free when she asked; a designer is to call and fix the design call.",
    handoffNote:
      "Gauri found us on Instagram and liked the kitchen photos. Possession in about a month; she wants to settle in three or four months after. She is travelling for work for a few days, so ask when she is back before proposing times. She asked what a flat like hers would come to; the agent gave only the standard line.",
    openQuestions: ["Which day suits her once she is back from travel?", "Does she have the floor plan to share before the call?"],
    tierReason: "All five criteria pass; no slot was free on her preferred day and she could not name another, so a designer will fix the time.",
    criteria: crit(["pass", "Design and the full work"], ["pass", "Baner, Pune"], ["pass", "Settle in three or four months after possession"], ["pass", "Our home, deciding ourselves"]),
  },

  // 17 Neel Chitale: Green, wanted to choose a time later
  17: {
    transcript: tx(300, [
      `A: ${OPEN}`,
      "U: Hello. I found you on Google. I need a designer for my flat.",
      "A: Thank you for calling. May I have your name?",
      "U: Neel Chitale.",
      "A: Thank you, Neel. Is the flat a home or an office?",
      "U: A home. 2BHK in Aundh.",
      "A: Roughly how big is it, in square feet?",
      "U: Around a thousand.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, both. The whole flat.",
      "A: Good. Is the flat ready for the designers to start?",
      "U: It's mine and it's empty now. I'd like to begin within two months.",
      "A: Thank you. And when would you need the project complete?",
      "U: There's no hurry for finishing. Sometime before summer is fine.",
      "A: That's helpful. How did you hear about the studio?",
      "U: I searched on Google and read your services page.",
      "A: Thank you. Based on what you've told me, I'd like to set up a design call with one of our designers. It's a short video or phone call of about twenty minutes. Which day would suit you?",
      "U: Right now I'm not sure about my schedule at work. Can I choose a time later?",
      "A: Of course. Would you like a designer to call you back to fix the time?",
      "U: Yes, please do that. Evenings are better.",
      "A: I'll note that. Evenings are better for you.",
      "U: Yes.",
      ...close(17, "I've noted a 2BHK home in Aundh, full design and execution, start within two months, and that a designer will call you in the evening to fix the design call."),
    ]),
    summary: "Neel Chitale, empty 2BHK in Aundh (about 1,000 sq ft), full design and execution, start within two months. Wants to choose the call time later; designer to call him in the evening.",
    handoffNote: "He prefers evening calls. No finish deadline beyond sometime before summer. The flat is his and empty. He read the services page before calling.",
    openQuestions: ["Which evening suits him for the design call?", "Does he have a floor plan or photos to share?"],
    tierReason: "All five criteria pass; the caller chose to fix the time later, so a designer will call to book it.",
    criteria: crit(["pass", "Yes, both. The whole flat"], ["pass", "2BHK in Aundh"], ["pass", "No hurry, before summer is fine"], ["pass", "It's mine and it's empty now"]),
  },

  // 18 Mitali Wagh: Amber, timeline undecided, callback
  18: {
    transcript: tx(336, [
      `A: ${OPEN}`,
      "U: Hi, I want to get my flat done up. I saw your website.",
      "A: Happy to help. May I have your name, please?",
      "U: Mitali Wagh.",
      "A: Thank you, Mitali. Is it a home or an office?",
      "U: Home. A 3BHK.",
      "A: Roughly how big is it, in square feet?",
      "U: About thirteen hundred and thirty.",
      "A: And which area is the flat in?",
      "U: Balewadi.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes. I want the whole thing handled.",
      "A: Good. When would you need the project complete?",
      "U: Honestly I haven't decided. We're still thinking about when to shift.",
      "A: That's all right. I'll note that. Is the flat ready for work to begin, or is it still with the builder?",
      "U: It's ready. We just haven't picked a date to move.",
      "A: Thank you. How did you hear about the studio?",
      "U: Google, I searched for interior designers in Pune.",
      "A: Thank you. Based on what you've told me, I'd like to set up a design call with one of our designers. It's a short video or phone call of about twenty minutes. Which day would suit you?",
      "U: Can the designer just call me first? I want to talk about the timing before I fix anything.",
      "A: Of course. A designer will call you back to take this forward.",
      "U: Okay, good.",
      "A: Is there a time of day you prefer?",
      "U: After six in the evening.",
      "A: I'll note that for the designer.",
      ...close(18, "I've noted a 3BHK home in Balewadi, full design and execution, a move date still to be decided, and that a designer will call you in the evening."),
    ]),
    summary: "Mitali Wagh, 3BHK in Balewadi (about 1,330 sq ft), wants design and execution. Move date not decided; designer to call her after six in the evening to talk timing.",
    handoffNote: "The flat is ready and hers. She has not picked a move date and asked to talk timing before booking. Prefers calls after six in the evening.",
    openQuestions: ["When does she expect to move in?", "Is there any work she wants done before that date?"],
    tierReason: "Timeline still unclear after one question (no completion date decided); everything else passes.",
    criteria: crit(["pass", "I want the whole thing handled"], ["pass", "Balewadi"], ["unclear", "Haven't decided when to shift"], ["pass", "Flat is hers, ready now"]),
  },

  // 19 Sandeep Limaye: Amber, structural changes, awaiting
  19: {
    transcript: tx(414, [
      `A: ${OPEN}`,
      "U: Hello, a friend recommended you. I want my flat redone.",
      "A: Thank you for calling. May I have your name?",
      "U: Sandeep Limaye.",
      "A: Thank you, Sandeep. Is this a home or an office?",
      "U: A home. 2BHK.",
      "A: Roughly how big, in square feet?",
      "U: Nine hundred and forty, about.",
      "A: And which area is it in?",
      "U: Pimple Saudagar.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, everything, from design to the finishing.",
      "A: That's clear. Is there anything in particular you have in mind for the layout?",
      "U: Yes. I want to take down the wall between the kitchen and the living room to open it up.",
      "A: Thank you for telling me. I'll note that for the designer.",
      "U: Is that something you do?",
      "A: I'll note that for the designer. They can speak to you about it properly.",
      "U: All right.",
      "A: When would you need the project complete?",
      "U: There's no fixed date. Sometime within the year.",
      "A: Thank you. How did you hear about the studio?",
      "U: A friend of mine, he got his house done by you last year.",
      "A: That's lovely to hear. Based on what you've told me, I'd like to set up a design call with one of our designers. It's a short video or phone call of about twenty minutes. Which day would suit you?",
      "U: I'd like my wife to be there as well. She isn't home today. Can someone call me so we can fix a day together?",
      "A: Of course. A designer will call you back to take this forward.",
      "U: Good. Thank you.",
      "A: Is there a time of day that works for both of you?",
      "U: Weekday evenings, after seven.",
      "A: I'll note that.",
      ...close(19, "I've noted a 2BHK home in Pimple Saudagar, full design and execution, a wish to open up the wall between kitchen and living room, and that a designer will call you on a weekday evening."),
    ]),
    summary: "Sandeep Limaye, 2BHK in Pimple Saudagar (about 940 sq ft). Wants design and execution and to remove the kitchen-living wall. Designer to call him on a weekday evening to fix a time with his wife.",
    handoffNote:
      "Referred by a friend whose home the studio did last year. He wants the wall between kitchen and living room taken down; the agent only noted it and gave no view. He wants his wife on the design call. Weekday evenings after seven.",
    openQuestions: ["Which wall exactly, and is it load-bearing?", "Which evening suits both him and his wife?"],
    tierReason: "Structural changes wanted (a wall between kitchen and living room); the other criteria pass, so a designer should speak to him first.",
    criteria: crit(["pass", "Everything, from design to the finishing"], ["pass", "Pimple Saudagar"], ["pass", "No fixed date, within the year"], ["pass", "Wants wife on the call, he is deciding"]),
  },

  // 20 Rutuja Mhatre: Amber, booked tomorrow 17:00, timeline unclear (family function)
  20: {
    transcript: tx(342, [
      `A: ${OPEN}`,
      "U: Hi, I saw your work on Instagram. I want a designer for our flat in Bavdhan.",
      "A: Happy to help. May I have your name, please?",
      "U: Rutuja Mhatre.",
      "A: Thank you, Rutuja. Is it a home or an office?",
      "U: Home. A 3BHK.",
      "A: Roughly how big is it, in square feet?",
      "U: Around twelve ninety.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, full work. I don't have time to manage vendors.",
      "A: Good. When would you need the project complete?",
      "U: We're planning a small family function at home in the first week of December. But it might move to March.",
      "A: I see. Is the date for the function fixed, or could it still change?",
      "U: It depends on my brother's leave. We'll know in two weeks.",
      "A: Thank you. I've noted that. How did you hear about the studio?",
      "U: Instagram, like I said. A friend tagged your page.",
      "A: That's lovely to hear. Is the flat ready for the designers to visit?",
      "U: Yes, we live in it now.",
      "A: Thank you.",
      ...book({
        dayReply: "Tomorrow, in the evening if I can.",
        slots: "I have 4 PM, 5 PM or 6 PM tomorrow. Which would you prefer?",
        pick: "Five o'clock, please.",
        emailLocal: "rutuja.mhatre",
        emailDomain: "example.com",
        confirm: "Your design call is booked for tomorrow at 5 PM. A designer will read your details before it, and the joining details will reach you by email.",
      }),
      ...close(20, "I've noted a 3BHK home in Bavdhan, design and execution, a family function in early December that may move, and your design call tomorrow at 5 PM."),
    ]),
    summary: "Rutuja Mhatre, 3BHK in Bavdhan (about 1,290 sq ft). Family function in early December may move to March, so the date is unclear. Design call booked tomorrow at 5 PM.",
    handoffNote: "She said the function date depends on her brother's leave and will be known in about two weeks. Ask on the call whether the home needs to be ready by then or whether March is the real target. They live in the flat now. Found us through a friend's tag on Instagram.",
    openQuestions: ["Is the early-December function fixed, or will it move to March?", "Does the whole flat need to be ready for the function?"],
    tierReason: "Timeline unclear: a family function in early December could move to March; the rest passes, so the call is booked for a designer to settle the date.",
    criteria: crit(["pass", "Full work, no time to manage vendors"], ["pass", "Flat in Bavdhan"], ["unclear", "Function first week of December, might move to March"], ["pass", "Our flat, we live in it"]),
  },

  // 21 Yash Kelkar: Amber, Hinglish, father decides, booked in two days at 11:30
  21: {
    transcript: tx(366, [
      `A: ${OPEN}`,
      "U: Hello, namaste. Mujhe apne flat ke liye interior designer chahiye. Google par aapka number mila.",
      "A: Namaste, bataiye, main madad karti hoon. Aapka naam kya hai?",
      "U: Yash Kelkar.",
      "A: Dhanyavaad, Yash ji. Ghar ke liye hai ya office ke liye?",
      "U: Ghar ke liye. 2BHK hai.",
      "A: Achha. Lagbhag kitne square feet ka hai?",
      "U: Around 1010 sq ft.",
      "A: Aur flat kis area mein hai?",
      "U: Hadapsar mein.",
      "A: Shukriya. Kya aap chahte hain ki studio design bhi kare aur kaam bhi poora karwaye?",
      "U: Haan, design aur execution dono. Poora flat.",
      "A: Theek hai. Aapko project kab tak poora chahiye?",
      "U: Abhi possession ki date fix nahi hai. Builder bol raha hai bas kuch mahine.",
      "A: Samajh gayi. Maine note kar liya. Kya flat ke liye faisla aap hi lenge?",
      "U: Actually, flat papa ke naam par hai. Main abhi sirf jaankari le raha hoon. Final decision papa hi lenge.",
      "A: Bilkul theek hai. Aap unko bhi design call par zaroor bulaiye, hum unka swagat karenge.",
      "U: Haan, wo retired hain, unhe subah ka time theek rehta hai.",
      "A: Achha. Aapne studio ke baare mein kaise suna?",
      "U: Google par dekha, aur reviews achhe the.",
      "A: Dhanyavaad. Mere paas ek suggestion hai. Aapki baat ke aadhaar par main ek design call set karna chahungi. Ye lagbhag bees minute ki video ya phone call hoti hai. Aapko kaunsa din theek rahega?",
      "U: Parso, subah ke time par.",
      "A: Main check karti hoon. Parso subah mere paas 10 AM aur 11:30 AM ke slots hain. Aap kaunsa chunenge?",
      "U: 11:30 theek rahega.",
      "A: Kya main aapka email address le sakti hoon, taaki joining details aap tak pahunch sakein?",
      "U: yash.kelkar at example dot com.",
      `A: Main dohra deti hoon. ${spell("yash.kelkar@example.com")}. Kya ye sahi hai?`,
      "U: Haan, bilkul sahi.",
      "A: Dhanyavaad. Aapki design call parso subah 11:30 AM par book ho gayi hai. Designer pehle aapki details padhenge. Papa ko zaroor saath rakhiye.",
      `A: Aapka best number ${phone(21)} hai, sahi?`,
      "U: Haan, sahi hai.",
      "A: Maine note kiya hai: Hadapsar mein 2BHK ghar, design aur execution, possession ki date abhi tay nahi, aur parso subah 11:30 baje design call jisme aapke papa bhi judenge. Thank you for calling Aangan Studio, aapka din shubh ho.",
      "U: Dhanyavaad, namaste.",
    ]),
    summary: "Yash Kelkar (Hinglish), 2BHK in Hadapsar (about 1,010 sq ft). Flat is in his father's name and the father decides; possession date not fixed. Design call booked in two days at 11:30 AM.",
    handoffNote: "The call was in Hinglish. Yash is gathering information; his father, who is retired and prefers mornings, makes the final decision and was invited to join the design call. Possession date depends on the builder and is not fixed.",
    openQuestions: ["Will his father join the call on the day?", "When is the builder expected to hand over?"],
    tierReason: "The caller is researching for his father, who decides; he has been invited to the call. Possession date is also not fixed. Everything else passes.",
    criteria: crit(["pass", "Design aur execution dono, poora flat"], ["pass", "Hadapsar mein"], ["pass", "Possession date fix nahi, builder kuch mahine bol raha hai"], ["unclear", "Final decision papa hi lenge"]),
  },

  // 22 Shreya Dandekar: Amber, booked four days after call at 11:00, timeline unsure
  22: {
    transcript: tx(390, [
      `A: ${OPEN}`,
      "U: Hello. I'd like to speak about doing up my flat in Kothrud.",
      "A: Happy to help. May I have your name, please?",
      "U: Shreya Dandekar.",
      "A: Thank you, Shreya. Is it a home or an office?",
      "U: Home. It's a 3BHK.",
      "A: Roughly how big is it, in square feet?",
      "U: About thirteen forty.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, I'd like one team to do everything.",
      "A: Good. Is the flat in Kothrud itself?",
      "U: Yes, near Karve Road.",
      "A: Thank you. When would you need the project complete?",
      "U: I'm not sure yet. My husband's job might move us, so I can't say.",
      "A: I understand. Is the flat ready for the designers to start, if you decide to go ahead?",
      "U: Yes, we live here.",
      "A: Thank you. I've noted that. How did you hear about the studio?",
      "U: A friend of mine in Aundh used you.",
      "A: That's lovely to hear. Is there anything you'd like to ask me?",
      "U: Can you tell me what it would cost, at least roughly?",
      `A: ${PRICE_LINE} I can book that for you right now if you'd like.`,
      "U: Fine. Let's book it.",
      ...book({
        dayReply: "Something four days from now, in the morning.",
        slots: "On that day I have 10 AM, 11 AM or 12 noon. Which would you prefer?",
        pick: "Eleven, please.",
        emailLocal: "shreya.dandekar",
        emailDomain: "example.com",
        confirm: "Your design call is booked for four days from now at 11 AM. A designer will read your details before it, and the joining details will reach you by email.",
      }),
      ...close(22, "I've noted a 3BHK home in Kothrud, design and execution, a timeline that is not yet clear, and your design call four days from now at 11 AM."),
    ]),
    summary: "Shreya Dandekar, 3BHK in Kothrud (about 1,340 sq ft). Timeline unclear because her husband's job may move them. Design call booked four days after the call, at 11 AM.",
    handoffNote: "A friend in Aundh recommended us. She asked about cost; the agent gave only the standard line. Her timing depends on her husband's job possibly moving the family, so confirm early on whether the project will go ahead soon. They live in the flat.",
    openQuestions: ["Is the family likely to move, and when will she know?", "If the project goes ahead, when should it be complete?"],
    tierReason: "Timeline unclear after one question (her husband's job may move the family); the rest passes, so the call is booked for the designer to settle it.",
    criteria: crit(["pass", "One team to do everything"], ["pass", "Kothrud, near Karve Road"], ["unclear", "Not sure yet, husband's job might move us"], ["pass", "We live here, I'm the owner"]),
  },

  // 23 Tejas Ghate: Amber, timeline unclear (around Diwali), awaiting
  23: {
    transcript: tx(318, [
      `A: ${OPEN}`,
      "U: Hi. I saw your page on Instagram. I want to redo my flat in Wakad.",
      "A: Thank you for calling. May I have your name?",
      "U: Tejas Ghate.",
      "A: Thank you, Tejas. Is it a home or an office?",
      "U: A home, a 2BHK.",
      "A: Roughly how big, in square feet?",
      "U: Nine ninety, around that.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, the whole thing, start to end.",
      "A: Good. When would you need the project complete?",
      "U: Around Diwali, I think. Maybe soon after, I haven't thought it through.",
      "A: Is there a day by which the flat must be ready, such as guests coming?",
      "U: Not exactly. My parents may visit for Diwali, but nothing is fixed.",
      "A: Thank you. I've noted that. Is the flat ready for the designers to start?",
      "U: Yes, it's empty right now.",
      "A: Good. How did you hear about the studio?",
      "U: Instagram, a reel about a Wakad flat.",
      "A: Thank you. Based on what you've told me, I'd like to set up a design call with one of our designers. It's a short video or phone call of about twenty minutes. Which day would suit you?",
      "U: Let me first talk to my parents about Diwali. Can someone call me?",
      "A: Of course. A designer will call you back to take this forward.",
      "U: Good. Not before noon, though. I work nights.",
      "A: I'll note that for the designer.",
      ...close(23, "I've noted a 2BHK home in Wakad, design and execution, a timeline around Diwali that is not fixed, and that a designer will call you after noon."),
    ]),
    summary: "Tejas Ghate, empty 2BHK in Wakad (about 990 sq ft), wants design and execution. Wants it done around Diwali, not fixed. Designer to call him after noon.",
    handoffNote: "He works nights, so call after noon. He wants to check with his parents, who may visit for Diwali, before fixing anything. The flat is empty. He found us through an Instagram reel.",
    openQuestions: ["Is a finish date around Diwali really needed, or can it be later?", "Does he want to bring his parents to the design call?"],
    tierReason: "Timeline unclear after one question (around Diwali, nothing fixed); everything else passes.",
    criteria: crit(["pass", "The whole thing, start to end"], ["pass", "Flat in Wakad"], ["unclear", "Around Diwali, maybe soon after, nothing fixed"], ["pass", "My flat, empty right now"]),
  },

  // 24 Charu Paranjape: Amber, timeline undecided, hesitant, awaiting
  24: {
    transcript: tx(288, [
      `A: ${OPEN}`,
      "U: Hello. I'm looking at designers for my flat. I found you on Google.",
      "A: Thank you for calling. May I have your name?",
      "U: Charu Paranjape.",
      "A: Thank you, Charu. Is this a home or an office?",
      "U: A home. 2BHK in Kharadi.",
      "A: Roughly how big, in square feet?",
      "U: Just over a thousand.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: I think so. I'm comparing a few studios first.",
      "A: That's fair. Do you want the studio to take care of design and the work together?",
      "U: Yes, together. I don't want different people for each part.",
      "A: Good. When would you need the project complete?",
      "U: I really can't say. Maybe this year, maybe next year.",
      "A: I understand. Is the flat ready for the designers to start?",
      "U: Yes, it's ready.",
      "A: Thank you. How did you hear about the studio?",
      "U: Google, as I said.",
      "A: Thank you. Based on what you've told me, I'd like to set up a design call with one of our designers. It's a short video or phone call of about twenty minutes. Which day would suit you?",
      "U: I'd rather not fix a day. I'm still comparing. Can someone call me once I'm ready?",
      "A: Of course. A designer will call you back to take this forward.",
      "U: Okay. Please don't call too early.",
      "A: I'll note that for the designer.",
      ...close(24, "I've noted a 2BHK home in Kharadi, design and execution together, a timeline you haven't decided, and that a designer will call you back."),
    ]),
    summary: "Charu Paranjape, 2BHK in Kharadi (about 1,000 sq ft), wants design and execution together. Timeline undecided and still comparing studios; designer to call her back, not too early.",
    handoffNote: "She is comparing several studios and did not want to fix a day. The timeline is open: this year or next. The flat is ready. Keep the first call light and avoid early mornings.",
    openQuestions: ["Is there any date she would like the flat ready by?", "What is she comparing studios on?"],
    tierReason: "Timeline unclear after one question (this year or next); everything else passes.",
    criteria: crit(["pass", "Yes, together, not different people for each part"], ["pass", "2BHK in Kharadi"], ["unclear", "Maybe this year, maybe next year"], ["pass", "My flat, it's ready"]),
  },

  // 25 Atul Rege: Amber, booked five days after call at 14:30, timeline not fixed
  25: {
    transcript: tx(384, [
      `A: ${OPEN}`,
      "U: Hello. I came across your studio on LinkedIn. I'd like to redo my apartment in Viman Nagar.",
      "A: Happy to help. May I have your name, please?",
      "U: Atul Rege.",
      "A: Thank you, Atul. Is it a home or an office?",
      "U: Home. A 3BHK.",
      "A: Roughly how big is it, in square feet?",
      "U: About fourteen seventy.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, that's what I want. Design and execution.",
      "A: Good. Is the apartment in Viman Nagar itself?",
      "U: Yes, near Symbiosis Road.",
      "A: Thank you. When would you need the project complete?",
      "U: I haven't fixed it. I travel a lot, so it depends on my schedule.",
      "A: I understand. Is there a date by which you'd like to be settled in?",
      "U: Not really. I'd like to know what's possible first.",
      "A: I've noted that. How did you hear about the studio?",
      "U: LinkedIn. A colleague shared a post about your office projects.",
      "A: That's lovely to hear. Is there anything you'd like to ask me?",
      "U: What will it cost?",
      `A: ${PRICE_LINE} I can book that for you right now if you'd like.`,
      "U: Yes, let's book.",
      ...book({
        dayReply: "Five days from now, after lunch.",
        slots: "On that day I have 2:30 PM, 4 PM or 5 PM. Which would suit you?",
        pick: "2:30, please.",
        emailLocal: "atul.rege",
        emailDomain: "example.com",
        confirm: "Your design call is booked for five days from now at 2:30 PM. A designer will read your details before it, and the joining details will reach you by email.",
      }),
      ...close(25, "I've noted a 3BHK home in Viman Nagar, design and execution, a timeline that is not fixed, and your design call five days from now at 2:30 PM."),
    ]),
    summary: "Atul Rege, 3BHK in Viman Nagar (about 1,470 sq ft). Wants design and execution; no fixed finish date because he travels a lot. Design call booked five days after the call, at 2:30 PM.",
    handoffNote: "Found us on LinkedIn through a colleague's post about our office projects. He travels often, so settle the work schedule early on the call. He asked about cost; the agent gave only the standard line.",
    openQuestions: ["How long is he away on his usual trips?", "When would he like to be settled in?"],
    tierReason: "Timeline unclear after one question (no fixed date, depends on his travel); everything else passes.",
    criteria: crit(["pass", "Design and execution"], ["pass", "Viman Nagar, near Symbiosis Road"], ["unclear", "Haven't fixed it, depends on my schedule"], ["pass", "My apartment"]),
  },

  // 26 Sunita Lele: Red, site in Nashik
  26: {
    transcript: tx(186, [
      `A: ${OPEN}`,
      "U: Hi, I want an interior designer for a flat I've bought.",
      "A: Thank you for calling. May I have your name?",
      "U: Sunita Lele.",
      "A: Thank you, Sunita. Is the flat a home or an office?",
      "U: A home, a 2BHK.",
      "A: Which area is the flat in?",
      "U: It's in Nashik, near College Road.",
      "A: Thank you. Just so I have it right, is the flat itself in Nashik?",
      "U: Yes. I live in Baner, but the flat I bought is in Nashik.",
      "A: I understand. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, everything.",
      "A: And when would you need it complete?",
      "U: By March, there's no rush.",
      "A: Thank you, Sunita. I'm sorry, but I have to be honest with you.",
      "U: Oh. Is something wrong?",
      "A: Not at all. The studio works only in Pune city and PCMC, because that is where our own vendors and teams are. A flat in Nashik is outside what we can do well.",
      "U: I see. I thought you could travel.",
      "A: I understand why you'd hope so. We'd rather be clear than promise something we can't deliver properly.",
      "U: That's fair.",
      "A: Before you go, may I ask how you heard about the studio?",
      "U: I found you on Google.",
      `A: Thank you, and thank you sincerely for thinking of us. ${FIT_PHRASE} Thank you for calling Aangan Studio, and I wish you all the best with your new flat.`,
      "U: Thank you, bye.",
    ]),
    summary: "Sunita Lele wants design and execution for a 2BHK flat in Nashik. It is outside Pune and PCMC, so the studio declined kindly.",
    handoffNote: null,
    openQuestions: [],
    tierReason: "Site is in Nashik, outside Pune city and PCMC; the studio has no vendor network there.",
    criteria: crit(["pass", "Yes, everything"], ["fail", "The flat I bought is in Nashik"], ["pass", "By March, no rush"], ["pass", "Flat she bought herself"]),
  },

  // 27 Manoj Barve: Red, ideas only
  27: {
    transcript: tx(156, [
      `A: ${OPEN}`,
      "U: Hello. I'm just looking for some ideas for my flat. Can you tell me what's trending?",
      "A: Thank you for calling. May I have your name?",
      "U: Manoj Barve.",
      "A: Thank you, Manoj. Where is the flat?",
      "U: Kothrud. It's a 2BHK.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Not really. I only want some ideas, maybe a designer to come and advise on colours.",
      "A: I see. And do you plan to do the work yourself afterwards?",
      "U: Yes, my own contractor will do it.",
      "A: Thank you for being so clear. I'm sorry, Manoj, but that is outside what the studio does.",
      "U: Oh. Why is that?",
      "A: We design the space and also carry out the work, from start to finish. Advice or ideas alone is not something we offer, and I can't suggest colours myself.",
      "U: I see. I thought a quick visit would be possible.",
      "A: I understand. It would be unfair to take your time for something we can't do well.",
      "U: Okay, that's fine.",
      "A: How did you hear about the studio?",
      "U: I saw it on Instagram.",
      `A: Thank you, and thank you sincerely for thinking of us. ${FIT_PHRASE} Thank you for calling Aangan Studio, and have a good day.`,
      "U: Thanks, bye.",
    ]),
    summary: "Manoj Barve, 2BHK in Kothrud. Wants ideas and colour advice and will use his own contractor. Advice-only, so the studio declined kindly.",
    handoffNote: null,
    openQuestions: [],
    tierReason: "Advice and ideas only, with his own contractor doing the work; not a design-and-execution project.",
    criteria: crit(["fail", "Only some ideas, my own contractor will do it"], ["pass", "Kothrud"], ["pass", null], ["pass", null]),
  },

  // 28 Reshma Inamdar: Red, single room styling/touch-up only
  28: {
    transcript: tx(204, [
      `A: ${OPEN}`,
      "U: Hi. My friend said you do lovely work. I want my bedroom freshened up.",
      "A: Thank you for calling. May I have your name?",
      "U: Reshma Inamdar.",
      "A: Thank you, Reshma. Which area is the flat in?",
      "U: Hadapsar.",
      "A: Thank you. What would you like done in the bedroom?",
      "U: Just a bit of a touch-up. New curtains, a couple of cushions, maybe rearranging the furniture.",
      "A: I see. Would you like our studio to redesign the room completely and also carry out the work?",
      "U: No, no. Nothing that big. I just want the room to look fresh.",
      "A: Thank you for explaining. Is it only the one room?",
      "U: Yes, only the bedroom.",
      "A: And when would you like it done?",
      "U: Over the next few weeks, nothing urgent.",
      "A: Thank you, Reshma. I'm sorry, but I have to be honest with you.",
      "U: Okay.",
      "A: The studio takes on a full room redesign with execution, or a larger project. Styling, curtains and rearranging furniture on its own is outside what we do.",
      "U: Oh, I see. I thought you could just advise.",
      "A: I understand. I wouldn't want to waste your time on something we can't do well.",
      "U: That's all right. Thank you for being clear.",
      "A: How did you hear about the studio?",
      "U: From a friend in Magarpatta.",
      `A: Thank you, and thank you sincerely for thinking of us. ${FIT_PHRASE} Thank you for calling Aangan Studio, and I hope the room comes out well.`,
      "U: Thank you, bye.",
    ]),
    summary: "Reshma Inamdar, one bedroom in Hadapsar. Wants a touch-up with new curtains and cushions, not a redesign with execution. Declined kindly.",
    handoffNote: null,
    openQuestions: [],
    tierReason: "Only styling and a touch-up of one room; no redesign or execution wanted.",
    criteria: crit(["fail", "Just a bit of a touch-up, new curtains, cushions"], ["pass", "Hadapsar"], ["pass", "Over the next few weeks, nothing urgent"], ["pass", null]),
  },

  // 29 Prasad Naik: Red, Mumbai (Hinglish-leaning English)
  29: {
    transcript: tx(174, [
      `A: ${OPEN}`,
      "U: Hello, I want a designer for my flat. Aapka work dekha hai, bahut achha hai.",
      "A: Thank you for calling. May I have your name?",
      "U: Prasad Naik.",
      "A: Thank you, Prasad. Is it a home or an office?",
      "U: Home. 3BHK.",
      "A: Which area is the flat in?",
      "U: It's in Mumbai, Andheri West.",
      "A: Thank you. Just so I have it right, is the flat itself in Mumbai?",
      "U: Yes. I work in Pune, but the flat is in Mumbai.",
      "A: I understand. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, full work.",
      "A: And when would you need it complete?",
      "U: Maybe in four or five months.",
      "A: Thank you, Prasad. I'm sorry, but the studio works only in Pune city and PCMC. Our teams and vendors are here, and I wouldn't want to promise work we can't carry out properly in Mumbai.",
      "U: Even if I pay for the travel of the team?",
      "A: I understand the thought. It's kind of you to offer. Our answer stays the same, because the work depends on our local vendors.",
      "U: Okay, I understand.",
      "A: How did you hear about the studio?",
      "U: Google.",
      `A: Thank you, and thank you sincerely for thinking of us. ${FIT_PHRASE} Thank you for calling Aangan Studio, and I wish you all the best with the flat.`,
      "U: Thanks, bye.",
    ]),
    summary: "Prasad Naik wants design and execution for a 3BHK in Andheri West, Mumbai. Outside Pune and PCMC, so the studio declined kindly.",
    handoffNote: null,
    openQuestions: [],
    tierReason: "Site is in Mumbai, outside Pune city and PCMC.",
    criteria: crit(["pass", "Yes, full work"], ["fail", "Flat is in Mumbai, Andheri West"], ["pass", "Maybe in four or five months"], ["pass", null]),
  },

  // 30 Divya Kamat: Red, plot with no building yet, site won't exist for over two years
  30: {
    transcript: tx(180, [
      `A: ${OPEN}`,
      "U: Hi. We've bought a plot in Baner and want to plan the interiors early.",
      "A: Thank you for calling. May I have your name?",
      "U: Divya Kamat.",
      "A: Thank you, Divya. Is the plot in Baner itself?",
      "U: Yes, it's in Baner. We'll build a house on it.",
      "A: I see. Has the construction started?",
      "U: No, not yet. We're still waiting for the plans to be approved.",
      "A: Thank you. Would you like our studio to design the interiors and also carry out the work?",
      "U: Yes, once the house is built.",
      "A: When would you need the house complete and ready to live in?",
      "U: Probably in two to three years.",
      "A: Thank you for telling me. I'm sorry, Divya, but I have to be honest.",
      "U: Okay.",
      "A: Our teams can take on a project once the site is ready, within about ten weeks or so. With the house still to be built, there is nothing for us to design and carry out for a long while.",
      "U: Even just planning ahead?",
      "A: I understand the wish to plan early. It wouldn't be fair to take your enquiry now and leave you waiting for years.",
      "U: That makes sense.",
      "A: How did you hear about the studio?",
      "U: Instagram. Your Baner project.",
      `A: Thank you, and thank you sincerely for thinking of us. ${FIT_PHRASE} Thank you for calling Aangan Studio, and I wish you the very best with the house.`,
      "U: Thank you, bye.",
    ]),
    summary: "Divya Kamat has a plot in Baner and the house is not yet started; she expects to need interiors in two to three years. Too far off for the studio, declined kindly.",
    handoffNote: null,
    openQuestions: [],
    tierReason: "Construction has not started and interiors are two to three years away, so there is no site to work on.",
    criteria: crit(["pass", "Yes, once the house is built"], ["pass", "Plot in Baner"], ["fail", "House not started, probably two to three years"], ["pass", null]),
  },

  // 31 Girish Apte: Red, only wants a free quote, his own contractor will do the work
  31: {
    transcript: tx(162, [
      `A: ${OPEN}`,
      "U: Hello. I need a quote for my flat. Can you send me a free quote?",
      "A: Thank you for calling. May I have your name?",
      "U: Girish Apte.",
      "A: Thank you, Girish. Where is the flat?",
      "U: Wakad. It's a 2BHK.",
      "A: Thank you. Could you tell me what you'd like our studio to do?",
      "U: Just give me the quote and the drawings. My contractor will do the actual work.",
      "A: I see. Would you like our studio to carry out the work as well?",
      "U: No. Only the numbers. What would it cost?",
      `A: ${PRICE_LINE}`,
      "U: So there's no free quote then?",
      "A: A designer goes through that in detail with clients whose project includes the studio carrying out the work.",
      "U: I only want the drawings and the quote, nothing more.",
      "A: Thank you for being clear, Girish. I'm sorry, but that is outside what the studio does. We design the space and also carry out the work. Drawings and a quote on their own are not something we offer.",
      "U: Okay. That's a pity.",
      "A: I understand. I wouldn't want to waste your time.",
      "U: Fine.",
      "A: How did you hear about the studio?",
      "U: Google.",
      `A: Thank you, and thank you sincerely for thinking of us. ${FIT_PHRASE} Thank you for calling Aangan Studio, and have a good day.`,
      "U: Bye.",
    ]),
    summary: "Girish Apte, 2BHK in Wakad. Wants only drawings and a quote and will use his own contractor. Not design and execution, so declined kindly.",
    handoffNote: null,
    openQuestions: [],
    tierReason: "Wants only drawings and a quote with his own contractor doing the work; not a design-and-execution project.",
    criteria: crit(["fail", "Just the quote and drawings, my contractor will do the work"], ["pass", "Wakad"], ["pass", null], ["pass", null]),
  },

  // 32 Ketaki Marathe: Red on timeline (under six weeks), later rescued by a designer
  32: {
    transcript: tx(294, [
      `A: ${OPEN}`,
      "U: Hi, a friend suggested your studio. I need my flat done up in Bavdhan.",
      "A: Thank you for calling. May I have your name?",
      "U: Ketaki Marathe.",
      "A: Thank you, Ketaki. Is it a home or an office?",
      "U: Home. A 2BHK.",
      "A: Roughly how big, in square feet?",
      "U: About nine hundred.",
      "A: Thank you. Would you like our studio to design the space and also carry out the work?",
      "U: Yes, the whole thing.",
      "A: Good. Is the flat in Bavdhan itself?",
      "U: Yes, in Bavdhan.",
      "A: Thank you. When would you need the project complete?",
      "U: By mid-November. My sister's engagement function is at our home.",
      "A: Thank you for telling me. A project like this usually needs a few weeks of design and then several weeks of execution, so that date would be very tight for us. If your date could move, we'd be glad to help. Could it?",
      "U: I'm afraid not. The function date is fixed, the families have already agreed.",
      "A: I understand. Thank you for answering so openly.",
      "U: Is there really no way?",
      "A: I'm sorry, Ketaki. With under six weeks, we couldn't design and carry out the work properly, and I wouldn't want to promise you something that falls short.",
      "U: That's disappointing, but I understand.",
      "A: Before you go, may I ask how you heard about the studio?",
      "U: A friend, she lives in Baner and you did her kitchen.",
      `A: That's lovely to hear. Thank you sincerely for thinking of us. ${FIT_PHRASE} Thank you for calling Aangan Studio, and I hope the function goes beautifully.`,
      "U: Thank you, bye.",
    ]),
    summary: "Ketaki Marathe, 2BHK in Bavdhan (about 900 sq ft), needs it complete by mid-November for a family function and the date cannot move. Declined by the agent; a designer later rescued the lead.",
    handoffNote:
      "The agent declined because the project had to be complete in under six weeks and the date could not move. A designer reviewed the call afterwards and booked a design call anyway. On the call, confirm what is really needed by the function (for example one or two rooms) and what can wait. Referred by a friend in Baner whose kitchen the studio did.",
    openQuestions: ["Is the function date truly fixed, or can any rooms wait?", "Which rooms must be ready first?"],
    tierReason: "Project must be complete by mid-November, under six weeks away; she was asked whether the date could move and said it cannot.",
    criteria: crit(["pass", "Yes, the whole thing"], ["pass", "Bavdhan"], ["fail", "By mid-November, the function date is fixed"], ["pass", "My flat, I'm deciding"]),
  },
};
